name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test:coverage
      - name: Fix code coverage paths
	      working-directory: ./coverage
	        run: |
	          sed -i 's/\/home\/runner\/work\/counter-app\/counter-app\//\/github\/workspace\//g' lcov.info
	          sed -i 's/\/home\/runner\/work\/counter-app\/counter-app\//\/github\/workspace\//g' sonar-cloud-reporter.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
